[package]
name = "adapter-cloud-hypervisor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = "0.2"
adapter-traits = { path = "../traits", version = "0.1.0" }
terrarium-fs = { path = "../../fs", version = "0.1.0" }
terrarium-network = { path = "../../network", version = "0.1.0" }
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["net", "time", "io-util"] }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
