[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
adapter-cloud-hypervisor = { path = "../adapter/cloud-hypervisor" }
adapter-traits = { path = "../adapter/traits" }
overlay = { path = "../overlay" }
num_cpus = "1"
futures = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
